name: 7SRbeta
favicon: null
layout_spectrum: 0
typography_spectrum: 0.81331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#3e0000'
    - '#7f1702'
    - '#442a1c'
    - '#003840'
  brandStrength: 0.31023766356520355
  lightness: 0.9040009379386902
  saturation: 0.7268217334058136
  rhythmicContrast: 0.18979090405628085
purpose: []
